name: Create Files
'on':
  push:
    branches:
      - main
jobs:
  create-files:
    runs-on: ubuntu-latest
    steps:
      - name: Create Files
        run: |
          echo "File content" > example.txt
          touch another_file.txt
